### ISSUE TITLE
Problem with hardware acceleration on some devices

### ISSUE THREAD

**Issue by akshayballal95** [StarlightSearch/EmbedAnything#33]
Facing issue

python3 examples/audio.py
```
Traceback (most recent call last):
  File "/Volumes/ashis_ssd/opensource/startlight_search/EmbedAnything/examples/audio.py", line 1, in <module>
    import embed_anything
  File "/Volumes/ashis_ssd/opensource/startlight_search/EmbedAnything/python/embed_anything/__init__.py", line 41, in <module>
    from .embed_anything import *
ImportError: dlopen(/Volumes/ashis_ssd/opensource/startlight_search/EmbedAnything/python/embed_anything/embed_anything.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_hgemm_'
```

**Comment by sonam-pankaj95** [comment]
This issue was solved, right?
